### ISSUE TITLE
Proposal: add byte type-literal b

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/vblang#295] opened 2018-04-25 15:12 UTC
VB.NET has the &B binary literal:
`Dim x = &B1010`
X will be integer.
It also will be useful if we use b as a type symbol for byte like this:
```
Dim b = 12b
Dim c = {1b, 2b, 3b}
```
so VB.NEt can infer that b is byte, and c is byte array

**Comment by Nukepayload2** [comment] 2018-04-25 15:16
Already proposed https://github.com/dotnet/vblang/issues/213

**Comment by MohammadHamdyGhanem** [comment] 2018-04-25 15:28
@Nukepayload2 
Thanks. Is there a way to fine tune the search to look in the titles only?

**Comment by Nukepayload2** [comment] 2018-04-25 15:37
Use the `in:title` qualifier. https://help.github.com/articles/searching-issues-and-pull-requests/

**Comment by AnthonyDGreen** [comment] 2018-06-10 08:42
@MohammadHamdyGhanem what do you think of proposal #213? Looked like the scenario itself, moreso than any particular proposal, didn't have a lot of support.

**Comment by reduckted** [comment] 2018-06-10 20:30
Well, #213 is basically a duplicate of #111, and neither of them have gone anywhere despite general agreement that it's a good idea.

It would be nice to see some of these "simple" ideas move forward.

**Comment by AnthonyDGreen** [comment] 2018-06-10 22:01
Wow. I duplicated my own proposal. So embarrassed.

**Comment by KathleenDollard** [comment] 2018-08-01 21:38
Dupe of #213

**Closed by KathleenDollard** 2018-08-01 21:38 UTC
