### ISSUE TITLE
VB should implicitly use CType when there is no + operator 

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/vblang#543] opened 2020-07-11 11:40 UTC
Suppose we have this class:
```VB.NET
Public Class Foo
    Dim Value As Integer

    Public Sub New(value As Integer)
        Me.value = value
    End Sub

    Public Shared Widening Operator CType(n As Foo) As Integer
        Return n.value
    End Operator

End Class
```

When I use this code:
```
  Dim x As New Foo(30)
  Dim a As Integer = 1 + x
```

I got the error:
> Operator '+' is not defined for types 'Integer' and 'IntegerRange'.

This is not the VB behavior I expect as:
1. The result is expected to be an integer.
2. also the other operand is an integer. So, the obvious action is to implicitly casting the IntegerRange to Integr
3. and the IntegerRange already has a Ctype operator to convert it to Integer.
4. moreover it is a widening Ctype so, no resk involved and strict should not complain about this (which is already of in my code but even if it is on).

In fact, I expect from VB to be clever enough to use this 
widening Ctype operator in any context where Integer can be valid, so that I don't need to write dozen of widening operators to convert to other numeric types bigger than integer!

**Comment by VBAndCs** [comment] 2020-07-11 21:55
mikernet pointed out that the code works fine in C# without ant conversion nor overriding the + operator! This was thee VB playground, so what did happen?

**Comment by paul1956** [comment] 2020-07-11 21:57
Shouldn't this be as below, I don't see how VB could know what the default value of the class should be. Also Visual Studio "should" generate all the operators for you. What I found in a web search is that what you want was removed in VB version 7, https://stackoverflow.com/questions/293215/default-properties-in-vb-net

```VB
Dim a As Integer = 1 + CType(x, Integer)
```
Below works as expected though I might be missing a few operators
```VB
' Licensed to the .NET Foundation under one or more agreements.
' The .NET Foundation licenses this file to you under the MIT license.
' See the LICENSE file in the project root for more information.

<Reflection.DefaultMember("Value")>
Public Class IntegerRange
    Private ReadOnly _anyOf() As Integer
    Private _range? As (Start As Integer, [End] As Integer)
    Private _value As Integer

    Public Sub New(value As Integer, anyOf() As Integer)
        _anyOf = anyOf
        Me.Set(value)
    End Sub

    Public Sub New(value As Integer, range As (Start As Integer, [End] As Integer))
        _range = range
        Me.Set(value)
    End Sub

    Public Sub New(range As (Start As Integer, [End] As Integer), anyOf() As Integer)
        _range = range
        _anyOf = anyOf
        Me.Set(_value)
    End Sub

    Public Sub New(anyOf() As Integer)
        _anyOf = anyOf
    End Sub

    Public Sub New(start As Integer, [end] As Integer)
        _range = (start, [end])
    End Sub

    Public Sub New(start As Integer, [end] As Integer, anyOf() As Integer)
        _range = (start, [end])
        _anyOf = anyOf
    End Sub

    Public ReadOnly Property Value As Integer
        Get
            Return _value
        End Get
    End Property

    Public Shared Operator -(n As IntegerRange) As Integer
        Return -n._value
    End Operator

    Public Shared Operator *(n As IntegerRange, i As Integer) As Integer
        Return n._value * i
    End Operator

    Public Shared Operator *(i As Integer, n As IntegerRange) As Integer
        Return i * n._value
    End Operator

    Public Shared Operator /(n As IntegerRange, i As Integer) As Integer
        Return n._value / i
    End Operator

    Public Shared Operator /(i As Integer, n As IntegerRange) As Integer
        Return i / n._value
    End Operator

    Public Shared Operator \(n As IntegerRange, i As Integer) As Integer
        Return n._value \ i
    End Operator

    Public Shared Operator \(i As Integer, n As IntegerRange) As Integer
        Return i \ n._value
    End Operator

    Public Shared Operator +(n As IntegerRange, i As Integer) As Integer
        Return n._value + i
    End Operator

    Public Shared Operator +(i As Integer, n As IntegerRange) As Integer
        Return i + n._value
    End Operator

    Public Shared Operator +(n As IntegerRange) As Integer
        Return n._value
    End Operator

    Public Shared Operator <>(n As IntegerRange, i As Integer) As Boolean
        Return n.Value <> i
    End Operator

    Public Shared Operator =(n As IntegerRange, i As Integer) As Boolean
        Return n.Value = i
    End Operator

    Public Shared Widening Operator CType(n As IntegerRange) As Integer
        Return n._value
    End Operator

    Public Sub [Set](n As Integer)
        If _anyOf?.Contains(n) Then
            _value = n
            Return
        End If

        If _range.HasValue AndAlso n >= _range.Value.Start AndAlso n <= _range.Value.End Then
            _value = n
            Return
        End If

        Throw New ArgumentOutOfRangeException(NameOf(n))
    End Sub

End Class
```

**Comment by VBAndCs** [comment] 2020-07-11 22:22
@paul1956
What brings default value here? This is a classical implicit conversion that VB always did.
If VB works like it should, (like C# does) then there is no need to write dozens of overloaded operators (need to do this for all numeric types not just Integer).
I see this as a bug in VB, and must be fixed.

**Comment by gilfusion** [comment] 2020-07-13 14:49
Did a little testing in LINQPad, and, as you said, the `+` operator doesn't implicitly convert. Neither did `-` or `*`. So it looks like an operator thing. Function calls do the implicit conversion correctly, of course.

Has this case in particular worked in past VB versions (like pre-Roslyn)? If so, it certainly would be a bug and hopefully one that would be fixed. If not, it would technically be a behavior change and unlikely to happen given the current .NET team position on VB.

Another question would be "whose currently-working code could be broken by making this change"? I suspect that's a deep discussion and one of the reasons it hasn't been changed already.

**Comment by jrmoreno1** [comment] 2020-07-13 23:34
@gilfusion : I don’t see how it would break working code, it doesn’t compile at the moment. The correct operator should have precedence, but if there isn’t one, the implicit conversion should be tried.

**Comment by gilfusion** [comment] 2020-07-16 14:55
@jrmoreno1 , you're probably right. I'm just trying to speculate on why it hasn't made it in before and what obstacles and unresolved details might come up if we tried to put it in. Along those lines...

Does that fact that VB (when `Option Strict` is off) has built-in conversions from `String` to (apparently) `Double` make a difference?

`"2" - 1` is an error in C# but `1` in VB. VB's design may have focused more on having more built-in conversions, either ignoring or overlooking ones defined in code, while C#'s design tried to limit its built-in conversions in favor of the ones defined in code.

(Aside: `"2" + 1` is `"21"` in C# but `3` in VB – VB's `+` operator only concatenates when you only have Strings or Chars.)

Also, if you had multiple implicit conversions (say, one to `Integer` and one to `Double`), which should be picked? Would it be confusing if different operators chose differently: `+`, `-`, `*`, and `\` might pick `Integer`, but `/` might go for `Double`, for example. Or should division go for `Integer` then convert it again to `Double` before doing the operator runs. Should we support implicitly converting twice – once with the conversion in code and then with the built-in conversion after that?

Also, since VB likes to convert strings to numbers in math operations, should we allow implicit conversions to `String` to play along, too?

**Comment by jrmoreno1** [comment] 2020-07-16 15:30
String to double or double to string via option strict off can't make a difference, and multiple implicit conversions don't happen --- you never go from string to integer to foo to bar to baz.

**Comment by VBAndCs** [comment] 2020-10-31 09:38
I reported a similar issue in dotnet/roslyn#49095, but @CyrusNajmabadi  said that it is by VB specifications. This can't be right as C# already treat this situation as expected. How come that C# allows a conversion  that VB forbids?

**Comment by Joe4evr** [comment] 2020-10-31 10:20
Because VB is a different language with different designs and goals. If it wasn't, VB would never have been brought onto .NET in the first place and MS would've told developers to switch to C#.

**Comment by VBAndCs** [comment] 2020-10-31 12:49
@Joe4evr 
This is not an answer.
Thanks.

**Comment by CyrusNajmabadi** [comment] 2020-10-31 15:00
> How come that C# allows a conversion that VB forbids?

They are not the same language. They have different rules. Just because c# allows something has no bearing on VB, and vice versa.

**Comment by CyrusNajmabadi** [comment] 2020-10-31 16:16
@Joe4evr 's comment is accurate and appropriate. These are two different languages governed by different specifications. C# is not just VB with lowercase keywords and a different grammar.  They have different features, semantics and capabilities.

**Comment by VBAndCs** [comment] 2020-10-31 18:50
@CyrusNajmabadi  
> They have different rules

VB allows widening conversions, and even in `Option Strict Off` mode (which is the defaults) allows narrowing conversions. So, what is the rule that turns this off when evaluating `Integer.+` operator?. If no such a rule, this is a bug.

**Comment by CyrusNajmabadi** [comment] 2020-10-31 19:08
That's not how the language works. There must be a rule to allow it. If there is no such rule, then it is not allowed. If you think the language spec allows for his, please link to the respective sections and quote the portions that support your reasoning. Without that, there can't be progress here.

**Comment by VBAndCs** [comment] 2020-10-31 19:31
This will make it more obvious:
```VB.NET
Class Foo
    Dim Value As Integer = 0

    Public Shared Widening Operator CType(f As Foo) As Integer
        Return f.Value
    End Operator

    Public Shared Operator +(f As Foo, x As Integer) As Foo
        Dim foo = New Foo()
        foo.Value = f.Value + x
        Return foo
    End Operator
End Class
```
If you try:
`Dim x As Integer = 1 + New Foo()`
VB says if can't convert 1 to Foo. But it can convert Foo to integer, and this is the right action, as the expected result is Integer. Even the left hand operand is Integer and `Integer.+` should have precedence here. This breaks the standard VB behaviour, and I think this is a recent Issue, at least specific to Roslyn not before.

**Comment by VBAndCs** [comment] 2020-10-31 19:35
Note that this works:
`Dim x As Integer = New Foo() + 1`

**Comment by VBAndCs** [comment] 2020-10-31 19:39
So, to make it work:
```
Class Foo
    Dim Value As Integer = 0

    Public Shared Widening Operator CType(f As Foo) As Integer
        Return f.Value
    End Operator

    Public Shared Operator +(f As Foo, x As Integer) As Foo
        Dim foo = New Foo()
        foo.Value = f.Value + x
        Return foo
    End Operator

    Public Shared Operator +(x As Integer, f As Foo) As Foo
        Dim foo = New Foo()
        foo.Value = f.Value + x
        Return foo
    End Operator
End Class
```

Now this works, involving casting the result back to Integer:
`Dim x As Integer = 1 + New Foo()`

**Comment by rskar-git** [comment] 2020-10-31 19:41
> So, to make it work...

Yep, that how it's done! Custom `+` isn't presumed to be the same as the built-in `+`; the custom `+` might care about order.

**Comment by CyrusNajmabadi** [comment] 2020-10-31 20:07
@VBAndCs 

> If you think the language spec allows for this, please link to the respective sections and quote the portions that support your reasoning. Without that, there can't be progress here.

**Comment by CyrusNajmabadi** [comment] 2020-10-31 20:14
> This breaks the standard VB behaviour, and I think this is a recent Issue, at least specific to Roslyn not before.

I can't find a VB compiler that allows this. It's possible you used some other compiler with a bug. If you think this works on another compiler please provide the information on it, as well as a repro showing how you invoked it along with the compiler result it produced

**Comment by VBAndCs** [comment] 2020-10-31 20:39
@CyrusNajmabadi  
I tried with VB 2008, but it has the same issue, with a slightly different message:
>
Error	1	Overload resolution failed because no accessible '+' can be called with these arguments:
    'Public Shared Operator +(f As Foo, x As Integer) As Foo': Value of type 'Integer' cannot be converted to 'ConsoleApplication1.Foo'

The `because no accessible '+' can be called ` is the real issue. There is an accessible '+' that can be called. If belongs to Integer. If VB sees it, it will do the suitable conversion (that is already provided).
Another point: Why does the order of the operands in the + operator matters? It is totally safe to the compiler to generate another signature of the operator with different order, that calls the original operator. I think the whole operator overloading needs a thorough review and a fresh design. Every time I overload an operator, I face unpleasant issues, and write too much code to get it work properly.

**Comment by CyrusNajmabadi** [comment] 2020-10-31 20:43
> I tried with VB 2008, but it has the same issue, 

I'm going to close this then as you have demonstrated this is not a regression

**Closed by CyrusNajmabadi** 2020-10-31 20:43 UTC

**Comment by CyrusNajmabadi** [comment] 2020-10-31 20:45
> Another point: Why does the order of the operands in the + operator matters? 

Because many operators are not commutative. Obvious examples are subtraction and division. However, even in some domains things are not commutative even for operators you expect. For example, multiplication can change meaning based on order of operations. So you are required to supply the right overloads so you can define the right semantics for your domain. The language doesn't guess here on your behalf

**Comment by CyrusNajmabadi** [comment] 2020-10-31 20:49
> and I think this is a recent Issue, at least specific to Roslyn not before.

In the future you will need to provide demonstrable evidence for these claims. They otherwise take up to much time and energy for people to investigate (esp. when they turn out to be wrong). Thank you

**Comment by VBAndCs** [comment] 2020-10-31 21:05
> multiplication can change meaning based on order of operations

This will has no effect. I am not asking for changing the operands order in the expression. I am asking to auto generate an operator overload with opposite order for operators like + and *. 

> I'm going to close this then as you have demonstrated this is not a regression
This is a proposal topic as its title suggests:
> VB should implicitly use CType when there is no + operator 

So, I am asking to change the behaviour and add a specification for that (if it doesn't exist). This means that LDM should discuss this and decide to accept or dismiss. So, technically. you should leave it open. But practically, we no nothing about LDM for month, so it doesn't matter.

**Comment by VBAndCs** [comment] 2020-11-02 00:16
from https://docs.microsoft.com/en-us/dotnet/visual-basic/reference/language-specification/expressions
> Given an operator type and a set of operands, operator resolution determines which operator to use for the operands. When resolving operators, user-defined operators will be considered first, using the following steps:
1.First, all of the candidate operators are collected. The candidate operators are all of the user-defined operators of the particular operator type in the source type and all of the user-defined operators of the particular type in the target type. If the source type and destination type are related, common operators are only considered once.
2.Then, overload resolution is applied to the operators and operands to select the most specific operator. In the case of binary operators, this may result in a late-bound call.

Note that the `first` word in `user-defined operators will be considered first` implies that intrinsic operators will be conseded in the next phase. This may be not clear for the implementers, and may be the source of this bug. So, the `Integer.+` opetrator must be in this list as there is an operand of type Integer, and above all the target type is Integer.

Now this is the second rule in resolutin rules:
> Any operand whose type is not defined for the operator is converted using the following steps and the operator is resolved against the new types:
◦The operand is converted to the next widest type that is defined for both the operator and the operand and to which it is implicitly convertible. ((My Class has a widinning CType to Integer. This is applicable))
◦If there is no such type, then the operand is converted to the next narrowest type that is defined for both the operator and the operand and to which it is implicitly convertible.
◦If there is no such type or the conversion cannot occur, a compile-time error occurs.
•Otherwise, the operands are converted to the wider of the operand types and the operator for that type is used. If the narrower operand type cannot be implicitly converted to the wider operator type, a compile-time error occurs

So, the source of this bug (that clarely violates the specs) is :
- the implementers misinterpreted the specs and drops the `Integer.+` becuase they missed the word `first`
- or the Integer.+ is in the list but VB missed it for some reason, as faling to see the CType operator defined in my class.
