### ISSUE TITLE
ObsoleteAttibute doesn't allow the [error] parameter to be specified explicitly in VB

### ISSUE THREAD

**Issue by paul1956** [dotnet/vblang#289] opened 2018-04-01 05:40 UTC
Even though [error] shows up in intellisense. If you don't include [error] :=  then it works. 
```
<Obsolete("Do not use Free, Use ClearAndFree instead.", [error]:=True)>
```
![image](https://user-images.githubusercontent.com/12789369/38170176-dacd1974-3532-11e8-9c9e-c848aed27693.png)

Error	BC30661	Field or property 'error' is not found.

Below works
```
<Obsolete("Do not use Free, Use ClearAndFree instead.", True)>
```
![image](https://user-images.githubusercontent.com/12789369/38170220-30da1d3e-3534-11e8-9471-3d6100eea3dc.png)

**Comment by reduckted** [comment] 2018-04-01 10:35
This is not specific to the `Obsolete` attribute. It applies to _all_ attributes.

This is by design. Attribute arguments are different to invocation arguments. From the spec:

> **[Attribute Arguments](https://github.com/dotnet/vblang/blob/master/spec/attributes.md#attribute-arguments)**
> Arguments to an attribute may take two forms: positional arguments and instance variable/property initializers. Any positional arguments to the attribute must precede the instance variable/property initializers. 

> **[Invocation Expressions](https://github.com/dotnet/vblang/blob/master/spec/expressions.md#invocation-expressions)**
> An argument list has two sections: positional arguments and named arguments. Positional arguments are expressions and must precede any named arguments. Named arguments start with an identifier that can match keywords, followed by := and an expression.

Notice that there is no mention of named arguments for attributes. Allowing named arguments for attributes would lead to ambiguity. Consider this example:

```vb
Public Class FooAttribute
    Inherits Attribute

    Public Sub New(bar As Integer)
    End Sub

    Public Sub New(bar As Integer, meep As Integer)
    End Sub

    Public Property Meep As Integer

End Class

<Foo(1, meep:=2)>
Public Class Test
End Class
```

Is `meep:=2` supposed to be a named parameter for the second constructor, or is it initializing the `Meep` property? Following the spec it is entirely unambiguous - it is initializing the `Meep` property because there is no such thing as named arguments in attribute arguments.

**Comment by paul1956** [comment] 2018-04-02 07:51
@reduckted how does it work without issue in C#?  Also the [] confused me, they are usually shown for optional arguments but I guess they are escaping the error.

**Comment by reduckted** [comment] 2018-04-02 08:47
@paul1956 I believe the syntax is different for C#. Named parameters use the syntax `name: value`, whereas property initialization in attributes uses the syntax `name = value`, so there would be no ambiguity.

```c#
[Foo(1, meep: 2)]  // Uses the second overload.
[Foo(1, meep = 2)] // Uses the first overload and sets the property (assuming the property was lowercased).
```

**Comment by paul1956** [comment] 2018-04-04 05:32
@reduckted does that mean that VB can't initialize meep in your example?  So far I have not run into any code using [Foo(1, meep = 2)] so maybe it doesn't matter.

**Comment by reduckted** [comment] 2018-04-04 05:39
It should work fine in VB - you just can't use named parameters.

```vb
<Foo(1, 2)>          ' Uses the second overload.
<Foo(1, meep:=2)>    ' Uses the first overload and sets the property.
<Foo(1, 2, meep:=3)> ' Uses the second overload and sets the property.
```

**Comment by KathleenDollard** [comment] 2018-04-09 00:14
@paul1956 Can we close this or is there still an open question?

**Comment by paul1956** [comment] 2018-04-09 00:35
@KathleenDollard The question is answered but it does seem VB has an issue with using Named Attribute Parameters. If that is never going to be address then you can close this.

**Comment by KathleenDollard** [comment] 2018-04-09 01:29
I'm not sure we would design attributes the way they are designed in the runtime if we were to design them today. The existence of property and constructor input is confusing. C# glosses over that, I think creating an ambiguity if @reduckted example [here[(https://github.com/dotnet/vblang/issues/289#issuecomment-377777644) used lower case meep in both cases. VB is explicit, imagine that :-)

Changing this for VB would I fear be breaking. 

"If that is never going to be address then you can close this."

I'm going to close this, but it can be reopened. Whether we address something is based on how compelling it is and that it is not breaking. Right now, I think fixing this would be breaking and I see other issues more compelling. If folks disagree, the ability to reopen is by design.

**Closed by KathleenDollard** 2018-04-09 01:29 UTC
