### ISSUE TITLE
Byte literals

### ISSUE THREAD

**Issue by AnthonyDGreen** [dotnet/vblang#111] opened 2017-06-28 19:34 UTC
There's no way to express a Byte in VB. It can be a pain in some cases involving Option Strict. It also seems arbitrary since all the other numeric types have a suffix. We discussed this in a previous LDM and came up with SB and UB as the literal suffix for signed byte and unsigned byte respectively.

```
Dim signed = 1SB
Dim unsigned = 255UB
```

Seems cheap and consistent.

**Comment by craigajohnson** [comment] 2017-06-28 20:00
Seems like a no-brainer.

In addition to SB, could just B also be added for (what I consider to be) the most common case - signed byte (either 1SB or 1B would be accepted)?

**Comment by reduckted** [comment] 2017-06-28 22:07
Why `SB`? Why not just `B`. It consistent with the other type literal characters.

|Literal type character|Data Type|
|-----------------------|-----------|
|`S`|`Short`|
|`US`|`UShort`|
|`I`|`Integer`|
|`UI`|`UInteger`|
|`L`|`Long`|
|`UL`|`ULong`|

https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/data-types/type-characters#forced-literal-types

**Comment by AnthonyDGreen** [comment] 2017-06-29 01:35
Because in Hex B is a digit. Also because Byte is inconsistent with the other types in that the "default" is unsigned, so we weren't sure people would see 255B and know that it's (crap, I've forgotten while writing this what it is)... Signed (and an overflow, technically). Lastly, since UB is by far the more common case it's not that important to optimize SB.

**Comment by reduckted** [comment] 2017-06-29 03:02
> Because in Hex B is a digit.

Ah yes, good point, because `&H1B` is an `Integer` today, but would become ambiguous if we used `B` as the type char.

I'm good with `UB` and `SB` then. Anything will be better than having to use `CByte()` 😀

**Comment by craigajohnson** [comment] 2017-06-29 03:12
^^ same as @reduckted! I hadn't thought of a suffix after a hex literal but of course.

**Comment by KathleenDollard** [comment] 2018-08-01 21:37
Dupe of #213

**Closed by KathleenDollard** 2018-08-01 21:37 UTC
Labels: Proposal
